# -*- coding: utf-8 -*-
"""project1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13VJ8Mfkj0co9cd1588s01Kgjg73Cvk4n

random password generator
"""

import random
letters = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o',
           'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z',
           'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O',
           'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']
numbers = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

symbols = ['!', '#', '$', '%', '&', '(', ')', '*', '+']

print ("HELLO, WELCOME TO THE PASSWORD GENERATOR!!!")

no_letter=int(input("Enter the number of letters you want in your password: "))
no_symbols=int(input("Enter the number of symbols you want in your password: "))
no_numbers=int(input("Enter the number of number you want in your password: "))

pass_list=[]

for char in range (0,no_letter):
  pass_list.append(random.choice(letters))
for char in range (0,no_symbols):
  pass_list.append(random.choice(symbols))
for char in range (0,no_numbers):
  pass_list.append(random.choice(numbers))

random.shuffle(pass_list)
print(pass_list)

password=" "
for char in pass_list:
  password+=char
print(f"password::",{password})